#!/usr/bin/env python3
"""
Reorganize downloaded IRS forms into forms/<year>/ subdirectories
based on metadata scraped from the IRS directory.

Usage: python3 scripts/organize-by-year.py

Reads forms/ looking for PDFs in any flat year directory (e.g. forms/2025/)
and moves them into the correct year directory based on the IRS description.

Requires: forms-metadata.json (generated by scrape-metadata.py)
"""

import os
import re
import json
import shutil

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.join(SCRIPT_DIR, "..")
FORMS_DIR = os.path.join(REPO_ROOT, "forms")
META_FILE = os.path.join(REPO_ROOT, "forms", "metadata.json")


def parse_year(description):
    """Extract tax year from an IRS form description string.

    IRS descriptions use two formats:
      '2025 Form 1040 (PDF)'   -> 4-digit year prefix
      '1225 Form 941 (PDF)'    -> MMYY prefix (December 2025)
    """
    desc = description.strip()
    # 4-digit year prefix (2000–2099)
    m = re.match(r"^(20\d\d)\s", desc)
    if m:
        return int(m.group(1))
    # MMYY prefix
    m = re.match(r"^(\d{2})(\d{2})\s", desc)
    if m:
        yy = int(m.group(2))
        return (2000 + yy) if yy < 50 else (1900 + yy)
    return None


def load_metadata():
    if not os.path.exists(META_FILE):
        print(f"ERROR: {META_FILE} not found.")
        print("Run scripts/scrape-metadata.py first to generate it.")
        raise SystemExit(1)
    with open(META_FILE) as f:
        records = json.load(f)
    mapping = {}
    for r in records:
        fname = r["filename"]
        year = parse_year(r["description"])
        mapping[fname] = year
    return mapping


def main():
    mapping = load_metadata()

    # Collect all PDFs currently in any forms/<something>/ directory
    to_move = []  # (current_path, filename)
    for entry in os.listdir(FORMS_DIR):
        subdir = os.path.join(FORMS_DIR, entry)
        if not os.path.isdir(subdir):
            continue
        if entry == "metadata.json":
            continue
        for fname in os.listdir(subdir):
            if fname.endswith(".pdf"):
                to_move.append((os.path.join(subdir, fname), fname))

    moved = 0
    already_correct = 0
    unknown = 0

    for src_path, fname in sorted(to_move, key=lambda x: x[1]):
        year = mapping.get(fname)
        if year is None:
            dest_dir = os.path.join(FORMS_DIR, "unknown")
            label = "unknown"
        else:
            dest_dir = os.path.join(FORMS_DIR, str(year))
            label = str(year)

        dest_path = os.path.join(dest_dir, fname)

        if src_path == dest_path:
            already_correct += 1
            continue

        os.makedirs(dest_dir, exist_ok=True)
        shutil.move(src_path, dest_path)
        print(f"  {fname:<55} -> {label}/")
        moved += 1
        if year is None:
            unknown += 1

    # Remove now-empty source directories
    for entry in os.listdir(FORMS_DIR):
        subdir = os.path.join(FORMS_DIR, entry)
        if os.path.isdir(subdir) and not os.listdir(subdir):
            os.rmdir(subdir)
            print(f"  Removed empty directory: forms/{entry}/")

    print()
    print(f"Done: {moved} moved, {already_correct} already in correct location, {unknown} placed in unknown/.")


if __name__ == "__main__":
    main()
